export const RENEW_TIMES = 'RENEW_TIMES'
export const HANDLE_TWO_COLLAPSED = 'HANDLE_TWO_COLLAPSED'
export const HANDLE_ONE_COLLAPSED = 'HANDLE_ONE_COLLAPSED'
export const HANDLE_START_TIMER = 'HANDLE_START_TIMER'
